apiVersion: apps/v1
kind: Deployment
metadata:
  name: githubactions-aks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: githubactions-aks
  template:
    metadata:
      labels:
        app: githubactions-aks
    spec:
      containers:
      - name: githubactions-aks
        image: sander987ru/nginx-github-actions:lab
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
