kind: Deployment
metadata:
  name: mysql-db
spec:
  serviceName: mysql-db
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
        - name: mysql-db
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: ${{ secrets.DB_PASSWORD }}
            - name: MYSQL_DATABASE
              value: dbinitial
          ports:
            - containerPort: 3306
              name: mysql-db
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-persistent-storage
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: azure-csi-pvc