# This is a basic workflow to buid Docker image and deploy it to AKS cluster


# Indicates when the workflow is triggered
on:
  push:
    branches:
      - 'master'
    paths:
     - 'docker/**' # Trigger the workflow only if changes are made in the docker/ directory or its subdirectories


# JWT Token permissions for Federation APP Registrarion
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

# Set ENVIRONMENT variables for AKS
env:
 rg_name: aks-tf
 aks_cluster_name: aks-cluster-tf

      
# List of jobs/actions the workflow is going to do
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout 
        uses: actions/checkout@v4


      # Extract the last part of the path after "webs/" for later image tagging
      - name: Extract tag from Dockerfile path
        run: |
          DOCKERFILE_PATH=$(grep -oP '(?<=COPY webs/).*' docker/Dockerfile | cut -d' ' -f1 | xargs basename)
          echo "DOCKERFILE_PATH=$DOCKERFILE_PATH" >> $GITHUB_ENV

          
      # Login to DockerHub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
       # Build docker image and push to Docker Hub 
      - name: Build and push
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nginx-github-actions:${{ env.DOCKERFILE_PATH }}


        # Set AKS context to connect  
      -  name: Azure Login
         uses: Azure/login@v1.4.6
         with:
           client-id: ${{ secrets.AZURE_CLIENT_ID }}
           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
      -  name: Azure Kubernetes set context
         uses: Azure/aks-set-context@v3.2
         with:
            # Azure credentials i.e. output of `az ad sp create-for-rbac --name XXXXX`
           # creds: ${{ secrets.AZURE_CREDENTIALS }}
            # Resource Group Name
            resource-group: ${{ env.rg_name }}
            # AKS Cluster Name
            cluster-name: ${{ env.aks_cluster_name }}
            
       # Deploy to k8s cluster
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v4.9
        with:        
          # Path to the manifest files which will be used for deployment.
          manifests: |
            k8s/deployment.yml
            k8s/service.yml
          action: deploy
